# Generated by Django 3.1.3 on 2020-11-18 07:11

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', multiselectfield.db.fields.MultiSelectField(default='480p', max_length=200, verbose_name=(('720p', '720p'), ('1080', '1080p'), ('720p', '480p'), ('360p', '360p')))),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('released_date', models.DateTimeField(blank=True, null=True)),
                ('az', models.URLField(blank=True, null=True)),
                ('full', models.URLField(blank=True, null=True, unique=True)),
                ('hashed_full', models.URLField(blank=True, null=True, unique=True)),
                ('click_times', models.IntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.name')),
                ('res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.resolution')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.season')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('released_date', models.DateTimeField(blank=True, null=True)),
                ('az', models.URLField(blank=True, null=True)),
                ('full', models.URLField(blank=True, null=True, unique=True)),
                ('hashed_full', models.URLField(blank=True, null=True, unique=True)),
                ('click_times', models.IntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.resolution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
