# Generated by Django 3.1 on 2020-12-02 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Initials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('az', models.URLField(blank=True, null=True)),
                ('full', models.URLField(blank=True, null=True, unique=True)),
                ('hashed_full', models.URLField(blank=True, null=True, unique=True)),
                ('click_times', models.IntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='2', max_length=50, null=True)),
                ('initial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='story.initials')),
            ],
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('az', models.URLField(blank=True, null=True)),
                ('full', models.URLField(blank=True, null=True, unique=True)),
                ('hashed_full', models.URLField(blank=True, null=True, unique=True)),
                ('click_times', models.IntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('no', models.TextField()),
                ('res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.resolution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(blank=True, max_length=5, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.name')),
            ],
        ),
        migrations.AddField(
            model_name='resolution',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.season'),
        ),
    ]
